version: "3"
services:
  app:
    container_name: redmine
    image: sameersbn/redmine
    environment:
      - DB_HOST=db
      - DB_NAME=redmine_production
      - DB_USER=root
      - DB_PASS=root
    links:
      - db
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./src/assets:/home/redmine/redmine/public/themes/minimalflat2/
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=redmine_production
